#!/bin/bash
# stage-RQB2/config
# Export RasQberry configuration variables to chroot environment

# Export initramfs configuration
export SKIP_INITRAMFS="${SKIP_INITRAMFS}"

# Export RasQberry build configuration
export RQB_REPO="${RQB_REPO}"
export RQB_GIT_USER="${RQB_GIT_USER}"
export RQB_GIT_BRANCH="${RQB_GIT_BRANCH}"
export RQB_GIT_REPO="${RQB_GIT_REPO}"
export RQB_STD_VENV="${RQB_STD_VENV}"
export RQB_CONFDIR="${RQB_CONFDIR}"
export RQB_PIGEN="${RQB_PIGEN}"
