#!/bin/bash -e
# stage-RQB2/99-verify-initramfs/00-run-chroot.sh
# Verify initramfs configuration based on SKIP_INITRAMFS variable

echo "=== Verifying initramfs configuration ==="
echo "SKIP_INITRAMFS=${SKIP_INITRAMFS:-not set}"

if [ "${SKIP_INITRAMFS}" = "1" ]; then
    echo "SKIP_INITRAMFS=1 set, verifying initramfs is disabled..."
    
    # Check 1: Verify configuration file exists and has correct setting
    if [ -f /etc/default/raspberrypi-kernel ]; then
        if grep -q "^INITRD=No" /etc/default/raspberrypi-kernel; then
            echo "✓ INITRD=No is correctly set in /etc/default/raspberrypi-kernel"
        else
            echo "✗ ERROR: INITRD=No not found in /etc/default/raspberrypi-kernel!"
            cat /etc/default/raspberrypi-kernel
            exit 1
        fi
    else
        echo "✗ ERROR: /etc/default/raspberrypi-kernel missing!"
        exit 1
    fi

    # Check 2: Verify kernel hook script exists
    if [ -x /etc/kernel/postinst.d/00-skip-initramfs ]; then
        echo "✓ Kernel postinst skip hook is installed and executable"
    else
        echo "✗ WARNING: Skip hook missing or not executable at /etc/kernel/postinst.d/00-skip-initramfs"
    fi

    # Check 3: Verify update-initramfs was diverted
    if dpkg-divert --list | grep -q "diversion of /usr/sbin/update-initramfs"; then
        echo "✓ update-initramfs has been diverted"
    else
        echo "⚠ WARNING: update-initramfs diversion not found (might not have been needed)"
    fi

    # Check 4: Verify mkinitramfs was diverted
    if dpkg-divert --list | grep -q "diversion of /usr/sbin/mkinitramfs"; then
        echo "✓ mkinitramfs has been diverted"
    else
        echo "⚠ WARNING: mkinitramfs diversion not found (might not have been needed)"
    fi

    # Check 5: Verify no initramfs files exist
    INITRAMFS_COUNT=$(find /boot -name "initrd*" -o -name "initramfs*" 2>/dev/null | wc -l || echo 0)
    if [ "$INITRAMFS_COUNT" -eq 0 ]; then
        echo "✓ No initramfs files in /boot (excellent!)"
    else
        echo "✗ ERROR: Found $INITRAMFS_COUNT initramfs files despite SKIP_INITRAMFS=1:"
        find /boot -name "initrd*" -o -name "initramfs*" -ls
        echo "These files will increase image size unnecessarily"
        # Don't exit with error, just warn
    fi

    # Check 6: Verify raspi-firmware config (if applicable)
    if [ -f /etc/default/raspi-firmware ]; then
        if grep -q "^INITRAMFS=no" /etc/default/raspi-firmware; then
            echo "✓ INITRAMFS=no set in /etc/default/raspi-firmware"
        else
            echo "⚠ WARNING: INITRAMFS=no not found in /etc/default/raspi-firmware"
        fi
    fi

    # Report space savings
    echo ""
    echo "💾 Estimated space saved by skipping initramfs: ~50-100MB"
    echo "⏱  Estimated build time saved: ~2-5 minutes"
    
    # Show boot directory size
    echo ""
    echo "Boot partition size: $(du -sh /boot 2>/dev/null | cut -f1 || echo 'unknown')"
    
else
    echo "SKIP_INITRAMFS not set to 1, checking normal initramfs generation..."
    
    # When not skipping, we expect initramfs files to exist (eventually)
    INITRAMFS_COUNT=$(find /boot -name "initrd*" -o -name "initramfs*" 2>/dev/null | wc -l || echo 0)
    if [ "$INITRAMFS_COUNT" -gt 0 ]; then
        echo "✓ Found $INITRAMFS_COUNT initramfs files (expected behavior):"
        find /boot -name "initrd*" -o -name "initramfs*" -exec ls -lh {} \; | awk '{print "  " $9 " (" $5 ")"}'
    else
        echo "⚠ No initramfs files found yet (might be generated by later packages)"
    fi
    
    # Check that diversions are NOT in place
    if dpkg-divert --list | grep -q -E "(update-initramfs|mkinitramfs)"; then
        echo "✗ WARNING: Found diversions that should not be present:"
        dpkg-divert --list | grep -E "(update-initramfs|mkinitramfs)"
    else
        echo "✓ No diversions in place (correct for normal operation)"
    fi
    
    # Show boot directory size
    echo ""
    echo "Boot partition size: $(du -sh /boot 2>/dev/null | cut -f1 || echo 'unknown')"
fi

echo ""
echo "=== End initramfs verification ==="

# Always exit successfully - this is just verification
exit 0