#!/bin/sh
# initramfs hook to include MMC/SD card drivers
# This ensures the initramfs can detect and mount the SD card partitions

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Core MMC/SD card drivers required for Raspberry Pi
manual_add_modules mmc_core
manual_add_modules mmc_block
manual_add_modules sdhci
manual_add_modules sdhci_brcmstb

# Also include the filesystem drivers we need
manual_add_modules ext4
manual_add_modules vfat

exit 0